import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouteLoader from "./Component/Loader/loader";
import { AlertCheckerProvider } from "./Component/AlertContext/alertcontext";

import RouteAlert from "./Component/RouteAlert/routealert";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartAir&UvMonitor",
  description: "Generated by create next app",
  icons:{
    icon: "/Picture/favicon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RouteLoader/> 
        <AlertCheckerProvider>
          <RouteAlert/>
        {children}
          </AlertCheckerProvider>
        
      </body>
    </html>
  );
}
